#!/bin/bash
SUDO=''
if (( $EUID != 0 )); then
    SUDO='sudo'
fi
$SUDO curl -s https://raw.githubusercontent.com/kesumin/Custom-MOTD-for-Ubuntu-22.04.3-LTS/main/motd-setup.sh -o /tmp240207
# $SUDO cat /tmp240207
$SUDO chmod +x /tmp240207
$SUDO bash /tmp240207
$SUDO rm /tmp240207
$SUDO rm motd-start